#!/usr/bin/env python3
"""Generate the LaTeX bodies of every auto-generated paper table.

Reads the canonical result files under ``data/`` and emits one ``\\\\``-
terminated row block per paper table to a single file (default
``paper_tables.tex`` at the repo root). Each block is preceded by a
``% === <label> ===`` separator so it can be located by grep or copied
into the corresponding ``tabular*`` block of the paper.

Tables emitted (paper labels):
  tab:main-hard               natural-vs-hard accuracy across 4 encoders
  tab:cross-model             base vs DPT, 11-ds natural mean + 875 hard
  tab:main                    abridged 7-model main results
  tab:full-main               full 25-model main results (= App A)
  tab:probes                  ideal-point scorer + 3 structural relaxations
  tab:scorer-extensions       ideal-point + 3 capacity-adders
  tab:rank-ablation           LoRA rank ablation
  tab:rank-saturation         per-topic scorer rank sweep
  tab:paired-test             participant-level Wilcoxon + McNemar
  tab:cluster-coherence       Remesh cluster within-across lift
  tab:likert-correlation      pooled Spearman with Likert ratings
  tab:probe-on-tuned          per-topic probe on base vs DPT-tuned encoder
  tab:probe-on-tuned-margin   margin decomposition (needs probe_margin
                              _decomposition.json — run the corresponding
                              experiment first)

Tables not emitted by this script:
  tab:example                 illustrative anchor/match/distractor row, manual
  tab:errors                  LLM-classified error categories. The classifier
                              lives at scripts/experiments/classify_errors.py
                              and writes data/results/error_classification
                              .json; the 6-category counts are stable and
                              kept hand-typed in the paper rather than auto-
                              emitted here.
  table:datasets              auto-generated by scripts/plotting/
                              table_dataset_stats.py (writes dataset_stats
                              .tex at the repo root).

Usage:
  python scripts/build_paper_tables.py                 # writes paper_tables.tex
  python scripts/build_paper_tables.py --stdout        # prints to stdout
  python scripts/build_paper_tables.py --only tab:main # filter to one label
"""
import argparse
import contextlib
import json
import statistics
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# --- the 11-dataset universe; abridged tables drop RTA for back-compat ----
DS11 = [
    "gsc_abortion_gen", "gsc_abortion_val", "gsc_chatbot_gen",
    "remesh_campus_protests", "remesh_foreign_intervention", "remesh_right_to_assemble",
    "polis_15_per_hour_seattle", "polis_american_assembly_bowling_green",
    "polis_brexit_consensus", "polis_canadian_electoral_reform", "polis_scoop_hivemind_ubi",
]
SHORT = {
    "gsc_abortion_gen": "AbG", "gsc_abortion_val": "AbV", "gsc_chatbot_gen": "Chat",
    "remesh_campus_protests": "Camp", "remesh_foreign_intervention": "Frgn",
    "remesh_right_to_assemble": "RTA",
    "polis_15_per_hour_seattle": "Seatl", "polis_american_assembly_bowling_green": "BG",
    "polis_brexit_consensus": "Brxt", "polis_canadian_electoral_reform": "Can",
    "polis_scoop_hivemind_ubi": "UBI",
}
DS_DISPLAY = {
    "gsc_abortion_gen":            "GSC Abortion (gen)",
    "gsc_abortion_val":            "GSC Abortion (val)",
    "gsc_chatbot_gen":             "GSC Chatbot (gen)",
    "remesh_campus_protests":      "Remesh Campus Protests",
    "remesh_foreign_intervention": "Remesh Foreign Interv.",
    "remesh_right_to_assemble":    "Remesh Right to Assemble",
    "polis_15_per_hour_seattle":         "Polis Seattle",
    "polis_american_assembly_bowling_green": "Polis Bowling Green",
    "polis_brexit_consensus":      "Polis Brexit",
    "polis_canadian_electoral_reform": "Polis Canadian",
    "polis_scoop_hivemind_ubi":    "Polis UBI",
}

# Cross-model encoders (Tab 2 + Tab 3): hf_id, slug, short display, full display.
CROSS_ENCODERS = [
    ("sentence-transformers/sentence-t5-xl",     "sentence_transformers_sentence_t5_xl",     "sentence-T5-XL",       "sentence-T5-XL"),
    ("intfloat/e5-large-v2",                     "intfloat_e5_large_v2",                     "e5-large-v2",          "e5-large-v2"),
    ("BAAI/bge-large-en-v1.5",                   "BAAI_bge_large_en_v1_5",                   "BGE-large-en-v1.5",    "BGE-large-en-v1.5"),
    ("sentence-transformers/all-mpnet-base-v2",  "sentence_transformers_all_mpnet_base_v2",  "all-mpnet-base-v2",    "all-mpnet-base-v2"),
]

# Models in the abridged Tab 4 (display order).
TAB4 = [
    "ST5-XL + DPT (ours)", "ST5-XL", "OAI text-emb-3-large", "ST5-Large",
    "BGE-large-en", "StanceAware-SBERT", "BGE-SparseCL (arguana)",
]

# All 25 base + DPT models in Tab 12 (display order).
TAB12 = [
    "ST5-XL + DPT (ours)", "ST5-XL", "OAI text-emb-3-large", "ST5-Large",
    "Voyage-4-large", "ST5-Base", "Voyage-4", "NLI-mpnet", "GTE-large",
    "MxBAI-embed-large", "BGE-large-en", "OAI text-emb-3-small",
    "Voyage-3-large", "Voyage-4-lite", "StanceAware-SBERT",
    "Paraphrase-MiniLM", "E5-large-v2", "all-mpnet-base", "all-distilroberta",
    "BGE-SparseCL (arguana)", "Arctic-embed-l", "all-MiniLM-L12",
    "all-MiniLM-L6", "Voyage-3", "Qwen2-1.5B-instruct", "Stella-en-1.5B",
]

# Display name -> data-source spec.
#   ('seeds', slug)       5-seed mean from data/models/best/<slug>/seed*/results.json
#   ('per_model', fname)  data/results/per_model/<fname>
SOURCES = {
    "ST5-XL + DPT (ours)":     ("seeds",     "sentence_transformers_sentence_t5_xl"),
    "ST5-XL":                  ("per_model", "base_t5_xl_all.json"),
    "OAI text-emb-3-large":    ("per_model", "base_text_embedding_3_large_all.json"),
    "ST5-Large":               ("per_model", "base_sentence_transformers_sentence_t5_large_all.json"),
    "BGE-large-en":            ("per_model", "base_BAAI_bge_large_en_v1.5_all.json"),
    "Voyage-4-large":          ("per_model", "base_voyage_4_large_all.json"),
    "ST5-Base":                ("per_model", "base_sentence_transformers_sentence_t5_base_all.json"),
    "Voyage-4":                ("per_model", "base_voyage_4_all.json"),
    "NLI-mpnet":               ("per_model", "base_sentence_transformers_nli_mpnet_base_v2_all.json"),
    "GTE-large":               ("per_model", "base_thenlper_gte_large_all.json"),
    "MxBAI-embed-large":       ("per_model", "base_mixedbread_ai_mxbai_embed_large_v1_all.json"),
    "OAI text-emb-3-small":    ("per_model", "base_text_embedding_3_small_all.json"),
    "Voyage-3-large":          ("per_model", "base_voyage_3_large_all.json"),
    "Voyage-4-lite":           ("per_model", "base_voyage_4_lite_all.json"),
    "StanceAware-SBERT":       ("per_model", "base_vahidthegreat_StanceAware_SBERT_all.json"),
    "Paraphrase-MiniLM":       ("per_model", "base_sentence_transformers_paraphrase_MiniLM_L6_v2_all.json"),
    "E5-large-v2":             ("per_model", "base_intfloat_e5_large_v2_all.json"),
    "all-mpnet-base":          ("per_model", "base_sentence_transformers_all_mpnet_base_v2_all.json"),
    "all-distilroberta":       ("per_model", "base_sentence_transformers_all_distilroberta_v1_all.json"),
    "BGE-SparseCL (arguana)":  ("per_model", "base_SparseCL_BGE_SparseCL_arguana_all.json"),
    "Arctic-embed-l":          ("per_model", "base_Snowflake_snowflake-arctic-embed-l-v2_0_all.json"),
    "all-MiniLM-L12":          ("per_model", "base_sentence_transformers_all_MiniLM_L12_v2_all.json"),
    "all-MiniLM-L6":           ("per_model", "base_sentence_transformers_all_MiniLM_L6_v2_all.json"),
    "Voyage-3":                ("per_model", "base_voyage_3_all.json"),
    "Qwen2-1.5B-instruct":     ("per_model", "base_Alibaba-NLP_gte-Qwen2-1_5B-instruct_all.json"),
    "Stella-en-1.5B":          ("per_model", "base_dunzhang_stella_en_1.5B_v5_all.json"),
}


# --- loaders ---------------------------------------------------------------

def load_seed_means(slug):
    """Mean over data/models/best/<slug>/seed*/results.json test_metrics."""
    files = sorted((ROOT / f"data/models/best/{slug}").glob("seed*/results.json"))
    if not files:
        return None
    accum = {}
    for p in files:
        for ds, v in json.load(open(p))["test_metrics"].items():
            accum.setdefault(ds, []).append(v)
    return {ds: statistics.mean(vs) for ds, vs in accum.items()}


def load_per_model(fname):
    p = ROOT / "data/results/per_model" / fname
    return json.load(open(p))["metrics"] if p.exists() else None


def metrics_for(name):
    kind, arg = SOURCES[name]
    return {"seeds": load_seed_means, "per_model": load_per_model}[kind](arg)


# --- formatting helpers ----------------------------------------------------

def fmt_pct(v, places=1):
    return f"{v*100:.{places}f}" if v is not None else "--"


def bold(s):
    return f"\\textbf{{{s}}}"


def fmt_pval(p):
    """Format a p-value as ``$X.X{\\times}10^{-Y}$`` matching the paper style."""
    if p is None or p != p:  # NaN
        return "--"
    if p >= 1.0:
        return "$1.0$"
    if p >= 0.1:
        return f"${p:.2f}$"
    s = f"{p:.1e}"
    mant, exp = s.split("e")
    return f"${mant}{{\\times}}10^{{{int(exp)}}}$"


# --- shared helpers for scorer-ablation tables ---------------------------

def _scorer_seed_macros(variant: str, source_file: str = "scorer_structural_ablation.json"):
    """Return ([nat_per_seed], [hard_per_seed]) — macro-mean across 11
    datasets for each seed of `variant`.
    """
    p = ROOT / "data/results" / source_file
    if not p.exists():
        return [], []
    d = json.load(open(p))
    if variant not in d:
        return [], []
    by_seed_nat, by_seed_hard = {}, {}
    for ds, by_seed in d[variant].items():
        for seed, r in by_seed.items():
            if r.get("test") is not None:
                by_seed_nat.setdefault(seed, []).append(r["test"])
            if r.get("hard_acc") is not None:
                by_seed_hard.setdefault(seed, []).append(r["hard_acc"])
    nat_seeds  = [statistics.mean(vs) for vs in by_seed_nat.values()  if vs]
    hard_seeds = [statistics.mean(vs) for vs in by_seed_hard.values() if vs]
    return nat_seeds, hard_seeds


def _fmt_seed_cell(vals, places=1):
    if not vals:
        return "  --"
    m = statistics.mean(vals) * 100
    sd = statistics.stdev(vals) * 100 if len(vals) > 1 else 0.0
    return f"{m:.{places}f} $\\pm$ {sd:.{places}f}"


# --- emitters -------------------------------------------------------------

def emit_main_hard_table():
    """Tab 2 (`tab:main-hard`): natural mean (11 ds) vs 875-triplet hard."""
    cache_path = ROOT / "data/results/hard_triplet_cosine_1k.json"
    if not cache_path.exists():
        print("% (hard_triplet_cosine_1k.json missing)")
        return
    cache = json.load(open(cache_path))
    print(f"% --- Tab 2 (main-hard, natural 11-ds mean vs 875 hard triplets) ---")
    print(f"% (label: tab:main-hard)")
    print()
    for hf_id, _slug, _display, full in CROSS_ENCODERS:
        if hf_id not in cache:
            print(f"% WARNING: {hf_id} missing from hard_triplet_cosine_1k.json")
            continue
        nat = cache[hf_id]["normal_mean"] * 100
        hard = cache[hf_id]["hard_acc"] * 100
        delta = hard - nat
        # Match paper convention: small two-digit hard accuracies get a
        # \phantom{0} for vertical alignment.
        hard_s = f"{hard:.1f}"
        if hard < 10:
            hard_s = f"\\phantom{{0}}{hard:.1f}"
        print(f"{full:<22} & {nat:.1f} & {hard_s} & {delta:+.1f} \\\\")


def emit_cross_model_table():
    """Tab 3 (`tab:cross-model`): base vs tuned, natural mean (11 ds), hard."""
    cache_path = ROOT / "data/results/hard_triplet_cosine_1k.json"
    cache = json.load(open(cache_path))
    rows = []
    for hf_id, slug, _short, full in CROSS_ENCODERS:
        seed_files = sorted((ROOT / f"data/models/best/{slug}").glob("seed*/results.json"))
        nat_seeds, hard_seeds = [], []
        for p in seed_files:
            r = json.load(open(p))
            nat_seeds.append(statistics.mean(r["test_metrics"].values()))
            hard_seeds.append(r["hard_eval_accuracy"])
        nat_tuned = statistics.mean(nat_seeds)
        nat_tuned_sd = statistics.stdev(nat_seeds) if len(nat_seeds) > 1 else 0
        hard_tuned = statistics.mean(hard_seeds)
        hard_tuned_sd = statistics.stdev(hard_seeds) if len(hard_seeds) > 1 else 0
        nat_base  = cache[hf_id]["normal_mean"]
        hard_base = cache[hf_id]["hard_acc"]
        rows.append((full, nat_base, nat_tuned, nat_tuned_sd,
                          hard_base, hard_tuned, hard_tuned_sd))

    print(f"% --- Tab 3 (cross-model, 11-ds natural mean, 5 seeds) ---")
    print(f"% (label: tab:cross-model; gain columns = tuned - base)")
    print()
    for d, nb, nt, nsd, hb, ht, hsd in rows:
        nat_t_s = f"{nt*100:.1f}\\,$\\pm$\\,{nsd*100:.2f}"
        hard_t_s = f"{ht*100:.1f}\\,$\\pm$\\,{hsd*100:.2f}"
        gn = f"$+{(nt-nb)*100:.1f}$" if nt - nb >= 0 else f"${(nt-nb)*100:.1f}$"
        gh = f"$+{(ht-hb)*100:.1f}$" if ht - hb >= 0 else f"${(ht-hb)*100:.1f}$"
        print(f"{d:<22} & {nb*100:>4.1f} & {nat_t_s:<18} & {hb*100:>5.1f} & {hard_t_s:<18} & {gn} & {gh} \\\\")


def emit_main_table(model_names, datasets, label, caption):
    rows = {}
    for name in model_names:
        m = metrics_for(name)
        rows[name] = {ds: (m or {}).get(ds) for ds in datasets}
        if any(v is None for v in rows[name].values()):
            missing = [ds for ds, v in rows[name].items() if v is None]
            print(f"% WARNING: {name} missing data for {missing}", flush=False)

    means = {n: statistics.mean(v for v in rows[n].values() if v is not None) for n in model_names}

    col_winners = {}
    for ds in datasets:
        vals = [(n, rows[n][ds]) for n in model_names if rows[n][ds] is not None]
        if vals:
            col_winners[ds] = max(vals, key=lambda x: x[1])[0]
    mean_winner = max(model_names, key=lambda n: means[n])

    print(f"% --- {caption} ---")
    print(f"% (label: {label}; bolding = column max)")
    print()
    for name in model_names:
        cells = []
        for ds in datasets:
            v = rows[name][ds]
            s = fmt_pct(v)
            if name == col_winners.get(ds):
                s = bold(s)
            cells.append(s)
        mean_s = f"{means[name]*100:.1f}"
        if name == mean_winner:
            mean_s = bold(mean_s)
        print(f"{name:<30} & " + " & ".join(cells) + f" & {mean_s} \\\\")


def emit_main_abridged():
    emit_main_table(TAB4,  DS11, "tab:main",      "Tab 4 (abridged main, 11 ds)")


def emit_main_full():
    emit_main_table(TAB12, DS11, "tab:full-main", "Tab 12 (full main, 11 ds)")


def emit_probe_ablation_table():
    """Tab 6 (`tab:probes`): metric baseline + 3 structural relaxations."""
    rows = [
        ("Ideal-point scorer \\emph{(ours)}",            "metric",
         "$-\\lVert L^\\top\\psi(a) - L^\\top\\psi(x)\\rVert^2$"),
        ("Nonlinear \\textit{[drops linearity]}",        "nonlinear",
         "$-\\lVert\\phi(\\psi(a)) - \\phi(\\psi(x))\\rVert^2$, shared MLP $\\phi$"),
        ("Asymmetric \\textit{[drops tied projection]}", "asymmetric",
         "$-\\lVert L_a^\\top\\psi(a) - L_x^\\top\\psi(x)\\rVert^2$, indep.\\ $L_a, L_x$"),
        ("Inner product \\textit{[drops distance]}",     "inner_prod",
         "$\\langle L^\\top\\psi(a), L^\\top\\psi(x)\\rangle$"),
    ]
    n_seeds = max(len(_scorer_seed_macros(v)[0]) for _, v, _ in rows)
    print(f"% --- Tab 6 (probes ablation, macro over 11 ds, {n_seeds} seeds) ---")
    print(f"% (label: tab:probes; bolded row = ideal-point baseline)")
    print()
    for label, variant, form in rows:
        nat_s, hard_s = _scorer_seed_macros(variant)
        nat_cell = _fmt_seed_cell(nat_s)
        hard_cell = _fmt_seed_cell(hard_s)
        bold_open  = "\\textbf{" if variant == "metric" else ""
        bold_close = "}"          if variant == "metric" else ""
        print(f"{bold_open}{label}{bold_close}  & {form}  & {nat_cell} & {hard_cell} \\\\")


def emit_scorer_extensions_table():
    """App E.4 (`tab:scorer-extensions`): metric baseline + 3 capacity-adders."""
    rows = [
        ("Ideal-point scorer (baseline)", "metric",
         "$-\\lVert L^\\top\\psi(a) - L^\\top\\psi(x)\\rVert^2$"),
        ("Anisotropic metric",            "anisotropic",
         "$-\\sum_k m_k (\\tilde\\psi_a^{(k)} - \\tilde\\psi_x^{(k)})^2$, $m\\in\\mathbb{R}^{20}_+$"),
        ("Per-user salience",             "salience",
         "$-\\sum_k w_k(\\psi(a))\\,(\\tilde\\psi_a^{(k)} - \\tilde\\psi_x^{(k)})^2$"),
        ("Free item bias",                "item_bias",
         "$-\\lVert\\tilde\\psi_a - \\tilde\\psi_x\\rVert^2 + w^\\top\\psi(x)$, $w\\in\\mathbb{R}^{d}$"),
    ]
    n_seeds = max(len(_scorer_seed_macros(v)[0]) for _, v, _ in rows)
    print(f"% --- App E.4 (scorer extensions, macro over 11 ds, {n_seeds} seeds) ---")
    print(f"% (label: tab:scorer-extensions)")
    print()
    for label, variant, form in rows:
        nat_s, hard_s = _scorer_seed_macros(variant)
        print(f"{label:<35}  & {form}  & {_fmt_seed_cell(nat_s)} & {_fmt_seed_cell(hard_s)} \\\\")


def emit_rank_saturation_table():
    """App E.5 (`tab:rank-saturation`): metric scorer at varying ranks."""
    ranks = [1, 2, 5, 10, 20, 50, 100]
    variants = [(r, "metric" if r == 20 else f"rank_{r}") for r in ranks]
    nat_cells, hard_cells = [], []
    for _, v in variants:
        nat_s, hard_s = _scorer_seed_macros(v)
        nat_cells.append(_fmt_seed_cell(nat_s))
        hard_cells.append(_fmt_seed_cell(hard_s))
    n_seeds = max(len(_scorer_seed_macros(v)[0]) for _, v in variants)
    print(f"% --- App E.5 (rank saturation, macro over 11 ds, {n_seeds} seeds) ---")
    print(f"% (label: tab:rank-saturation)")
    print()
    print("Rank $r$     & " + " & ".join(str(r) for r in ranks) + " \\\\")
    print("Natural (\\%) & " + " & ".join(nat_cells) + " \\\\")
    print("Hard (\\%)    & " + " & ".join(hard_cells) + " \\\\")


def emit_likert_correlation_table():
    """App E.8 (`tab:likert-correlation`): pooled Spearman rank correlation."""
    p = ROOT / "data/results/likert_correlation.json"
    if not p.exists():
        print("% (likert_correlation.json missing — run scripts/experiments/likert_correlation.py)")
        return
    d = json.load(open(p))
    rows = [
        ("\\texttt{gsc\\_abortion\\_gen}", "gsc_abortion_gen"),
        ("\\texttt{gsc\\_abortion\\_val}", "gsc_abortion_val"),
        ("\\texttt{gsc\\_chatbot\\_gen}",  "gsc_chatbot_gen"),
    ]
    print("% --- App E.8 (Likert correlation, pooled Spearman) ---")
    print("% (label: tab:likert-correlation; bolded = best per row)")
    print()
    for label, ds in rows:
        if ds not in d: continue
        ms = d[ds]
        n = ms.get("base", {}).get("n_pairs", 0)
        cells = {m: ms[m]["spearman_pooled"] for m in ("base", "tuned", "proj") if m in ms}
        winner = max(cells, key=cells.get)
        def f(m):
            v = cells.get(m)
            s = f"{v:.3f}" if v is not None else "  --"
            return f"\\textbf{{{s}}}" if m == winner else s
        print(f"{label:<32} & {n:>4} & {f('base')} & {f('tuned')} & {f('proj')} \\\\")


def emit_rank_ablation_table():
    """App C.1 (`tab:rank-ablation`): LoRA rank sweep, single seed, mean over test ds.

    Paper convention drops `remesh_right_to_assemble` (10-dataset mean).
    """
    ranks = [4, 8, 16, 32, 64]
    means = []
    for r in ranks:
        p = ROOT / f"data/models/best/lora_rank_ablation/r{r}/results.json"
        if not p.exists():
            means.append(None)
            continue
        d = json.load(open(p))
        ds10 = {k: v for k, v in d["test_metrics"].items()
                if k != "remesh_right_to_assemble"}
        means.append(statistics.mean(ds10.values()) * 100)
    if all(m is None for m in means):
        print("% (data/models/best/lora_rank_ablation/r*/results.json missing)")
        return
    print(f"% --- App C.1 (LoRA rank ablation, single seed, mean over test datasets) ---")
    print(f"% (label: tab:rank-ablation; bolded = column max)")
    print()
    print("LoRA rank $r$       & " + " & ".join(str(r) for r in ranks) + " \\\\")
    valid = [m for m in means if m is not None]
    best = max(valid)
    cells = []
    for m in means:
        if m is None:
            cells.append("--")
        elif abs(m - best) < 1e-9:
            cells.append(bold(f"{m:.1f}"))
        else:
            cells.append(f"{m:.1f}")
    print("Mean test acc.\\ (\\%) & " + " & ".join(cells) + " \\\\")


def emit_paired_test_table():
    """App B (`tab:paired-test`): per-participant paired test, 11 ds + pooled."""
    p = ROOT / "data/results/paired_test_dpt_vs_base.json"
    if not p.exists():
        print("% (paired_test_dpt_vs_base.json missing — run scripts/experiments/participant_paired_test.py)")
        return
    d = json.load(open(p))
    print(f"% --- App B (participant-level paired test, DPT vs base ST5-XL) ---")
    print(f"% (label: tab:paired-test)")
    print()
    for r in d["per_dataset"]:
        ds = r["dataset"]
        name = DS_DISPLAY.get(ds, ds)
        n = r["n_participants"]
        base = r["base_mean"] * 100
        tuned = r["tuned_mean"] * 100
        delta = (r["tuned_mean"] - r["base_mean"]) * 100
        delta_s = f"$+{delta:.1f}$" if delta >= 0 else f"${delta:.1f}$"
        wp = fmt_pval(r["wilcoxon_p"])
        mp = fmt_pval(r["mcnemar_p"])
        print(f"{name:<25} & {n:>3} & {base:>4.1f} & {tuned:>4.1f} & {delta_s} & {wp} & {mp} \\\\")
    pl = d["pooled"]
    n_total = pl["n_participants"]
    base_tot = sum(r["base_mean"] * r["n_participants"] for r in d["per_dataset"]) / n_total * 100
    tuned_tot = sum(r["tuned_mean"] * r["n_participants"] for r in d["per_dataset"]) / n_total * 100
    pooled_delta = pl["mean_diff"] * 100
    pooled_delta_inner = f"+{pooled_delta:.1f}" if pooled_delta >= 0 else f"{pooled_delta:.1f}"
    print(f"\\midrule")
    print(f"\\textbf{{Pooled}}             & \\textbf{{{n_total}}} & "
          f"\\textbf{{{base_tot:.1f}}} & \\textbf{{{tuned_tot:.1f}}} & "
          f"$\\boldsymbol{{{pooled_delta_inner}}}$ & "
          f"$\\boldsymbol{{{fmt_pval(pl['wilcoxon_p'])[1:-1]}}}$ & "
          f"$\\boldsymbol{{{fmt_pval(pl['mcnemar_p'])[1:-1]}}}$ \\\\")


def emit_cluster_coherence_table():
    """App E.7 (`tab:cluster-coherence`): Remesh user clustering lift."""
    p = ROOT / "data/results/cluster_coherence.json"
    if not p.exists():
        print("% (cluster_coherence.json missing — run scripts/experiments/cluster_coherence.py)")
        return
    d = json.load(open(p))
    paper_ds = [
        ("remesh_campus_protests",      "Campus Protests"),
        ("remesh_foreign_intervention", "Foreign Intervention"),
        ("remesh_right_to_assemble",    "Right to Assemble"),
    ]
    ks = [3, 5, 8, 10]
    print(f"% --- App E.7 (cluster-coherence lift, 5 km-seed mean per cell) ---")
    print(f"% (label: tab:cluster-coherence; bolded = best per row)")
    print()
    datasets_block = d.get("datasets", d)
    for i, (ds, label) in enumerate(paper_ds):
        if i > 0:
            print("\\midrule")
        if ds not in datasets_block:
            print(f"% WARNING: {ds} missing from cluster_coherence.json")
            continue
        emb = datasets_block[ds]["by_embedding"]
        rows = []
        for k in ks:
            cells = {}
            for geom in ("base", "tuned", "proj"):
                run = next((r for r in emb.get(geom, {}).get("k_runs", []) if r["k"] == k), None)
                cells[geom] = run["seed_summary"]["macro_lift_mean"] * 100 if run else None
            rows.append(cells)
        for j, (k, cells) in enumerate(zip(ks, rows)):
            avail = {g: v for g, v in cells.items() if v is not None}
            winner = max(avail, key=avail.get) if avail else None
            def f(g):
                v = cells[g]
                if v is None: return "--"
                s = f"{v:.1f}"
                return bold(s) if g == winner else s
            head = f"\\multirow{{{len(ks)}}}{{*}}{{{label}}}" if j == 0 else ""
            print(f"{head:<40} & {k:>2} & {f('base')} & {f('tuned')} & {f('proj')} \\\\")


def emit_probe_on_tuned_table():
    """App E.6 (`tab:probe-on-tuned`): probe fit on base vs tuned encoder."""
    pb = ROOT / "data/results/scorer_structural_ablation.json"
    pt = ROOT / "data/results/scorer_structural_ablation_tuned.json"
    if not (pb.exists() and pt.exists()):
        print("% (scorer_structural_ablation[_tuned].json missing — see README)")
        return
    base = json.load(open(pb))["metric"]
    tuned = json.load(open(pt))["metric"]
    print(f"% --- App E.6 (per-topic probe on base vs tuned encoder) ---")
    print(f"% (label: tab:probe-on-tuned; bolded per row, separately for nat & hard)")
    print()
    nat_macro = {"base": [], "tuned": []}
    hard_macro = {"base": [], "tuned": []}
    for ds in DS11:
        cells = {}
        for tag, src in (("base", base), ("tuned", tuned)):
            if ds not in src:
                cells[tag] = (None, None, None, None)
                continue
            seeds = list(src[ds].values())
            tests = [s["test"] for s in seeds if s.get("test") is not None]
            hards = [s["hard_acc"] for s in seeds if s.get("hard_acc") is not None]
            cells[tag] = (
                statistics.mean(tests) * 100 if tests else None,
                statistics.stdev(tests) * 100 if len(tests) > 1 else 0.0,
                statistics.mean(hards) * 100 if hards else None,
                statistics.stdev(hards) * 100 if len(hards) > 1 else 0.0,
            )
        nb = cells["base"]; nt = cells["tuned"]
        # Strict winner only — ties leave both unbolded (matches paper).
        def winner(b, t):
            if b is None or t is None: return None
            if b > t: return "base"
            if t > b: return "tuned"
            return None
        nat_winner = winner(nb[0], nt[0])
        hard_winner = winner(nb[2], nt[2])
        def f(tag, idx_m, idx_s, win_tag):
            m, sd = cells[tag][idx_m], cells[tag][idx_s]
            if m is None: return "--"
            s = f"{m:.1f} $\\pm$ {sd:.1f}"
            return bold(s) if tag == win_tag else s
        name = DS_DISPLAY.get(ds, ds)
        print(f"{name:<25} & {f('base',0,1,nat_winner)} & {f('tuned',0,1,nat_winner)} "
              f"& {f('base',2,3,hard_winner)} & {f('tuned',2,3,hard_winner)} \\\\")
        for tag in ("base", "tuned"):
            if cells[tag][0] is not None: nat_macro[tag].append(cells[tag][0])
            if cells[tag][2] is not None: hard_macro[tag].append(cells[tag][2])
    print("\\midrule")
    nat_b = statistics.mean(nat_macro["base"]); nat_t = statistics.mean(nat_macro["tuned"])
    hard_b = statistics.mean(hard_macro["base"]); hard_t = statistics.mean(hard_macro["tuned"])
    def fm(v, win):
        s = f"{v:.1f}"
        return bold(s) if win else s
    print(f"\\textbf{{Macro mean}}      & {fm(nat_b, nat_b>nat_t)} & {fm(nat_t, nat_t>nat_b)} "
          f"& {fm(hard_b, hard_b>hard_t)} & {fm(hard_t, hard_t>hard_b)} \\\\")


def emit_probe_on_tuned_margin_table():
    """App E.6 bis (`tab:probe-on-tuned-margin`): margin decomposition."""
    p = ROOT / "data/results/probe_margin_decomposition.json"
    if not p.exists():
        print("% (probe_margin_decomposition.json missing — run "
              "scripts/experiments/probe_margin_decomposition.py)")
        return
    d = json.load(open(p))
    print(f"% --- App E.6 bis (probe-on-tuned margin decomposition) ---")
    print(f"% (label: tab:probe-on-tuned-margin)")
    print()
    for ds in DS11:
        if ds not in d:
            print(f"% WARNING: {ds} missing")
            continue
        rec = d[ds]
        b = rec["base"]; t = rec["tuned"]
        ip_b = b["ip_margin"]; ip_t = t["ip_margin"]
        ratio = ip_t / ip_b if ip_b not in (0, None) else None
        nb_b = b["norm_diff"]; nb_t = t["norm_diff"]
        def s(v):
            return f"$+{v:.2f}$" if v >= 0 else f"${v:.2f}$"
        ratio_s = f"{ratio:.1f}" if ratio is not None else "--"
        name = DS_DISPLAY.get(ds, ds)
        print(f"{name:<25} & {s(ip_b)} & {s(ip_t)} & {ratio_s} & {s(nb_b)} & {s(nb_t)} \\\\")


# --- registry --------------------------------------------------------------

EMITTERS = [
    ("tab:main-hard",              emit_main_hard_table),
    ("tab:cross-model",            emit_cross_model_table),
    ("tab:main",                   emit_main_abridged),
    ("tab:full-main",              emit_main_full),
    ("tab:probes",                 emit_probe_ablation_table),
    ("tab:scorer-extensions",      emit_scorer_extensions_table),
    ("tab:rank-ablation",          emit_rank_ablation_table),
    ("tab:rank-saturation",        emit_rank_saturation_table),
    ("tab:paired-test",            emit_paired_test_table),
    ("tab:cluster-coherence",      emit_cluster_coherence_table),
    ("tab:likert-correlation",     emit_likert_correlation_table),
    ("tab:probe-on-tuned",         emit_probe_on_tuned_table),
    ("tab:probe-on-tuned-margin",  emit_probe_on_tuned_margin_table),
]


def main():
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument("--out", default=str(ROOT / "paper_tables.tex"),
                    help="output path (default: paper_tables.tex at repo root)")
    ap.add_argument("--stdout", action="store_true",
                    help="print to stdout instead of writing a file")
    ap.add_argument("--only", action="append", default=None, metavar="LABEL",
                    help="emit only this label (repeatable)")
    args = ap.parse_args()

    valid = [k for k, _ in EMITTERS]
    targets = args.only or valid
    bad = [t for t in targets if t not in valid]
    if bad:
        print(f"unknown label(s): {bad}\nvalid: {valid}", file=sys.stderr)
        sys.exit(2)

    def emit_all(file):
        with contextlib.redirect_stdout(file):
            for label, fn in EMITTERS:
                if label not in targets:
                    continue
                print("=" * 70)
                print(f"% === {label} ===")
                fn()
                print()

    if args.stdout:
        emit_all(sys.stdout)
    else:
        out_path = Path(args.out)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        with open(out_path, "w") as f:
            emit_all(f)
        print(f"wrote {out_path}", file=sys.stderr)


if __name__ == "__main__":
    main()
